---
kind: pipeline
type: kubernetes
name: default

concurrency:
  limit: 1

steps:
  - name: test
    image: node:10.15
    environment:
      AUTH0_DOMAIN:
        from_secret: AUTH0_DOMAIN
      AUTH0_CLIENT_ID:
        from_secret: AUTH0_API_CLIENT_ID
      AUTH0_CLIENT_SECRET:
        from_secret: AUTH0_API_CLIENT_SECRET
      AUTH0_AUTHORIZATION_EXTENSION_URL:
        from_secret: AUTH0_AUTHORIZATION_EXTENSION_URL
    commands:
    - npm install
    - npm test

  - name: build + publish
    image: node:10.15
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
    - npm run build
    - echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > .npmrc
    - npm publish --access public
    # when:
    #   branch:
    #   - master

trigger:
  event:
    include:
    - push
